# Each route describes how and incoming URL will be processed by Platform.sh

"https://{default}/":
  type:upstram
  upstream:"ll_project:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"